json.id user.id
json.username user.username
json.profile_visibility user.profile_visibility
json.user_profile user.profile
json.favorites_count user.favorites.count
json.watched_movies_count user.watched_movies.count
json.saved_movies_count user.saved_movies.count
json.reviews_count user.reviews.count
json.followers_count user.followers.count
json.following_count user.followed.count